local_clutter_gtkmm_libs = $(top_builddir)/clutter-gtk/clutter-gtkmm/libclutter-gtkmm-$(API_VER).la

LIBS  = $(CLUTTER_GTKMM_LIBS) $(local_clutter_gtkmm_libs) 

all_includes = -I$(top_srcdir)/clutter-gtk \
               $(CLUTTER_GTKMM_CFLAGS)

DEFS = @DEFS@
DEFAULT_INCLUDES =
INCLUDES = -I. -I$(srcdir) $(strip $(all_includes))

